#!/usr/bin/env python3
#
#   Greenland -- a Python based scripting environment.
#   Copyright (C) 2015-2017  M E Leypold.
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
#   02110-1301 USA.

# * --- Context

import tests.local
from   greenland.testing.simple import test

from greenland.errors import Error
import re
import sys

# * --- Test Infrastructure

class SomeError(Error):
    message = "Some error happened, severity={baz}"

    help    = """
              This message is raised when some error happens.
              The value of baz (here: {baz}) indicates the
              level of severity.
              """

    info    = """
              foo: {foo}
              bar: {baz}
              """

class AnotherError(Error):
    message = "Another error happened, severity={baz}"

def raise_this(err):
    err.raise_here(__stackframe__=-1)

# * --- Tests
    
e = SomeError(foo=1,baz=456)                   # this must be line 36

test.check( e.get_oneline(), "==", sys.argv[0]+":36: SomeError: Some error happened, severity=456")
test.check( e.get_message(), "==", "Some error happened, severity=456")
test.check( e.get_info(), "==", 'foo: 1\nbar: 456')

try:
    raise e                                    # doesn't reset location captured in __init__

except Exception as x:
    test.check( e.get_message(), "==", "Some error happened, severity=456")
    test.check( e.get_oneline(), "==", sys.argv[0]+":36: SomeError: Some error happened, severity=456")

e = SomeError(foo=2,baz=456)

try:
    e.raise_here()                               # this must be line 52
except Exception as x:
    test.check( e.get_message(), "==", "Some error happened, severity=456")
    test.check( e.get_oneline(), "==", sys.argv[0]+":52: SomeError: Some error happened, severity=456")

e = SomeError(foo=3,baz=456)

try:
    e.raise_here()                               # this mus be line 60
except Exception as x:
    test.check( e.get_message(), "==", "Some error happened, severity=456")
    test.check( e.get_oneline(), "==", sys.argv[0]+":60: SomeError: Some error happened, severity=456")

    
# Note: Not testing Help + Default info so far.

